### ISSUE TITLE
PaintGL and GLWidget

### ISSUE THREAD

**Issue by stuffnex** [marialarsson/tsugite#2]
Hello, first of all thanks for your job. It's amazing and I can't wait to test it and realize something out of it.
Unfortunately I have an issue:
The program runs but in the terminal I have this error:
```
Traceback (most recent call last):
  File "Tsugite_app.py", line 92, in paintGL
    self.display.update()
AttributeError: 'GLWidget' object has no attribute 'display'
```
All the dependency looks satisfied but I am not really proficient. I could not find content on forums so here I am.

I using Ubuntu 20.04.1 LTS, 64-bit.
Thanks for your time

**Comment by marialarsson** [comment]
Dear Stuffnex,
Great to hear that you are testing it out! 
I am using windows 10, and it works. Unfortunately, I do not know the answer to your question.
If you find an answer, maybe post it here as it might be of interest for others.
Otherwise, maybe try running the code on Windows 10 (or the executable file available for download from the project website, also for Windows 10).
Hope it works out.
/Maria

**Comment by dvdrbls** [comment]
I had the same issue in my laptop, but it runs well in my desktop, only difference is my desktop has a dedicated GPU I don't know if it makes sense to you

**Comment by marialarsson** [comment]
Interesting..... It is hard for me to debug it... because it works on my computer. But if anybody finds a solution, please post it here to help other people with the same issue!

**Comment by dvdrbls** [comment]
I did install the ones you mention, and this happens, also noted the  one use in my desktop is the executable, haven't tried to run the code

C:\Users\Dell\Desktop\tsugite\setup>pip3 install PyOpenGL PyOpenGL_accelerate
Requirement already satisfied: PyOpenGL in c:\python38\lib\site-packages (3.1.5)
Collecting PyOpenGL_accelerate
  Downloading PyOpenGL_accelerate-3.1.5-cp38-cp38-win_amd64.whl (340 kB)
     |████████████████████████████████| 340 kB 656 kB/s
Installing collected packages: PyOpenGL-accelerate
Successfully installed PyOpenGL-accelerate-3.1.5

C:\Users\Dell\Desktop\tsugite\setup>pip3 install PyOpenGL
Requirement already satisfied: PyOpenGL in c:\python38\lib\site-packages (3.1.5)

C:\Users\Dell\Desktop\tsugite\setup>python3 tsugite_app.py
Unable to load numpy_formathandler accelerator from OpenGL_accelerate
Traceback (most recent call last):
  File "tsugite_app.py", line 74, in initializeGL
    self.display = Display(self,self.type)
  File "C:\Users\Dell\Desktop\tsugite\setup\Display.py", line 12, in __init__
    self.create_color_shaders()
  File "C:\Users\Dell\Desktop\tsugite\setup\Display.py", line 53, in create_color_shaders
    self.shader_col = OpenGL.GL.shaders.compileProgram(OpenGL.GL.shaders.compileShader(vertex_shader, GL_VERTEX_SHADER),
  File "C:\Python38\lib\site-packages\OpenGL\GL\shaders.py", line 235, in compileShader
    raise ShaderCompilationError(
OpenGL.GL.shaders.ShaderCompilationError: ('Shader compile failure (0): b"ERROR: 0:4: \'#extension\' :  \'GL_ARB_explicit_uniform_location\' is not supported\\nERROR: 0:8: \'location layout qualifier\' :  not supported  \\nERROR: 0:9: \'location layout qualifier\' :  not supported  \\nERROR: 0:10: \'location layout qualifier\' :  not supported  \\nERROR: 0:15: \'transform\' : undeclared identifier \\nERROR: 0:15: \'translate\' : undeclared identifier \\nERROR: 0:15: \'position\' : undeclared identifier \\nERROR: 0:15: \'constructor\' : not enough data provided for construction \\nERROR: 0:16: \'newColor\' : undeclared identifier \\nERROR: 0:16: \'myColor\' : undeclared identifier \\nERROR: 0:17: \'outTexCoords\' : undeclared identifier \\nERROR: 0:17: \'inTexCoords\' : undeclared identifier \\n\\n"', [b'\n        #version 330\n        #extension GL_ARB_explicit_attrib_location : require\n        #extension GL_ARB_explicit_uniform_location : require\n        layout(location = 0) in vec3 position;\n        layout(location = 1) in vec3 color;\n        layout(location = 2) in vec2 inTexCoords;\n        layout(location = 3) uniform mat4 transform;\n        layout(location = 4) uniform mat4 translate;\n        layout(location = 5) uniform vec3 myColor;\n        out vec3 newColor;\n        out vec2 outTexCoords;\n        void main()\n        {\n            gl_Position = transform* translate* vec4(position, 1.0f);\n            newColor = myColor;\n            outTexCoords = inTexCoords;\n        }\n        '], GL_VERTEX_SHADER)

**Comment by marialarsson** [comment]
hmm.. maybe the issue is that I have a variable called "display" and "Display" (with a capital D) is already a taken name by opengl. I will change the name of my variable to see if that helps... Ill let you know when it is done.

**Comment by marialarsson** [comment]
I pushed the changes. But I am not sure it will make a difference...

**Comment by marialarsson** [comment]
Just to double check versions... 
pip show pyopengl (command line) gives this result. Do you have the same installation of PyOpenGl?

Name: PyOpenGL
Version: **3.1.5**
Summary: **Standard** OpenGL bindings for Python
Home-page: http://pyopengl.sourceforge.net
Author: Mike C. Fletcher
Author-email: mcfletch@vrplumber.com
License: BSD

**Comment by dvdrbls** [comment]
Yes is the same

C:\Users\Dell\Desktop\tsugite-master\setup>pip3 show pyopengl
Name: PyOpenGL
Version: 3.1.5
Summary: Standard OpenGL bindings for Python
Home-page: http://pyopengl.sourceforge.net
Author: Mike C. Fletcher
Author-email: mcfletch@vrplumber.com
License: BSD
Location: c:\python38\lib\site-packages
Requires:
Required-by:

**Comment by stuffnex** [comment]
Hi, I have an update.
I made some tests, updated all the requirements up to the right version and downloaded the new code.

I believe we're on the right way. Maybe because linux is case-sensitive?
Now I have another error, with same effect on the UI, I can see a pattern in here: might be another capital letter in a variable like "d/Display"?

``Traceback (most recent call last):
  File "Tsugite_app.py", line 92, in paintGL
    self.show.update()
AttributeError: 'builtin_function_or_method' object has no attribute 'update'
``
Might it be a good lead? Thank you!

**Comment by DanielJoyce** [comment]
Well here is your problem from one error:
```
OpenGL.GL.shaders.ShaderCompilationError: ('Shader compile failure (0): b"ERROR: 0:4: '#extension' : 'GL_ARB_explicit_uniform_location' is not supported
```

If this from your laptop, it's gpu may not support the features needed by a shader. This would explain why a discrete desktop gpu worked.

**Comment by hmikihth** [comment]
@stuffnex 

Could you try now my fork? I have made some changes and it works well for me on Linux (blackPanther OS).

**Comment by stuffnex** [comment]
@hmikihth, thank you for your work, unfortunately I still have the same output as before:

```
AttributeError: 'builtin_function_or_method' object has no attribute 'view'
Traceback (most recent call last):
  File "Tsugite_app.py", line 92, in paintGL
    self.show.update()
AttributeError: 'builtin_function_or_method' object has no attribute 'update'
Traceback (most recent call last):
  File "Tsugite_app.py", line 182, in mouseMoveEvent
    if self.show.view.dragged:
AttributeError: 'builtin_function_or_method' object has no attribute 'view'
Traceback (most recent call last):
  File "Tsugite_app.py", line 182, in mouseMoveEvent

```
Again, UI loads in no time tho the frame where the joint should be displayed is blank
see this [screenshot](https://imgur.com/a/rhmf4Ls) if might help...
I was so excited for this app.. It's a pain to not make it work on my laptop..

Thank you all for your support, please come ahead if you have insights!

**Comment by hmikihth** [comment]
Hi, I see the line numbers are not the same, so that was not my fork. I guess you do not have the hashbang (#!/usr/bin/env python3) in the first line, and maybe you started it with python2 instead of python3.

How did you start the script? 

python tsugite_app.py

OR

python3 tsugite_app.py

OR

./tsugite_app.py

**Comment by mskyttner** [comment]
Linux build for container exposing the app through the browser (no hardware acceleration, "softpipe" rendering) works around hardware issues with graphics drivers at the cost of slower rendering, see https://github.com/marialarsson/tsugite/pull/25.
